import asyncio
import json
import logging
import re
from typing import Dict

import aiohttp


logger = logging.getLogger(__name__)

_DEFAULT_ENDPOINT = "http://127.0.0.1:11434"
_DEFAULT_MODEL = "qwen2.5:3b"
_VALID_VERDICTS = {"dga", "benign", "uncertain"}


def _uncertain(domain: str, error: str) -> Dict:
    return {
        "domain": domain,
        "llm_verdict": "uncertain",
        "llm_reasoning": "",
        "error": error,
    }


def _parse_json_response(response_text: str) -> Dict:
    try:
        parsed = json.loads(response_text)
    except json.JSONDecodeError:
        json_match = re.search(
            r"```(?:json)?\s*(\{.*?\})\s*```",
            response_text,
            re.DOTALL,
        )
        if json_match:
            parsed = json.loads(json_match.group(1))
        else:
            start = response_text.find("{")
            end = response_text.rfind("}") + 1
            if start < 0 or end <= start:
                raise ValueError("Could not parse JSON from Ollama response")
            parsed = json.loads(response_text[start:end])

    if not isinstance(parsed, dict):
        raise ValueError("Ollama response JSON is not an object")

    return parsed


async def judge_domain(domain: str, config: Dict) -> Dict:
    llm_config = config.get("llm", {}) if isinstance(config, dict) else {}
    if not isinstance(llm_config, dict):
        llm_config = {}

    endpoint = llm_config.get("ollama_endpoint") or _DEFAULT_ENDPOINT
    model = llm_config.get("model") or _DEFAULT_MODEL

    prompt = (
        "Classify whether this domain appears to be generated by a "
        "Domain Generation Algorithm. Use only the domain string. "
        "Return JSON only in this exact shape: "
        '{"llm_verdict":"dga|benign|uncertain",'
        '"llm_reasoning":"short reasoning"}\n'
        f"Domain: {domain}"
    )

    payload = {
        "model": model,
        "prompt": prompt,
        "stream": False,
        "format": "json",
        "options": {
            "temperature": 0.2,
            "repeat_penalty": 1.3,
            "num_predict": 256,
        },
    }

    try:
        timeout = aiohttp.ClientTimeout(total=30)
        async with aiohttp.ClientSession(timeout=timeout) as session:
            async with session.post(
                f"{endpoint.rstrip('/')}/api/generate",
                json=payload,
            ) as response:
                if response.status != 200:
                    body = await response.text()
                    return _uncertain(
                        domain,
                        f"Ollama API error {response.status}: {body[:200]}",
                    )

                data = await response.json()
                parsed = _parse_json_response(data.get("response", ""))

                verdict = parsed.get("llm_verdict")
                if verdict not in _VALID_VERDICTS:
                    return _uncertain(
                        domain,
                        f"Invalid llm_verdict: {verdict!r}",
                    )

                reasoning = parsed.get("llm_reasoning", "")
                if not isinstance(reasoning, str):
                    reasoning = str(reasoning)

                return {
                    "domain": domain,
                    "llm_verdict": verdict,
                    "llm_reasoning": reasoning,
                    "error": None,
                }

    except aiohttp.ClientConnectorError as exc:
        logger.warning("[LLM-DGA] Cannot connect to Ollama: %s", exc)
        return _uncertain(domain, str(exc) or "Ollama connection failed")
    except asyncio.TimeoutError:
        logger.warning("[LLM-DGA] Ollama request timed out")
        return _uncertain(domain, "Ollama request timed out")
    except Exception as exc:
        logger.warning("[LLM-DGA] Judge failed: %s", exc)
        return _uncertain(domain, str(exc) or exc.__class__.__name__)
