import asyncio
import hashlib
import json
import logging
import os
import re
from typing import Dict

import aiohttp


logger = logging.getLogger(__name__)

_DEFAULT_ENDPOINT = "http://127.0.0.1:11434"
_DEFAULT_MODEL = "qwen2.5:3b"
_VLLM_ENDPOINT_KEY = "vllm_base_url"
_VLLM_MODEL_OVERRIDE = "qwen3-8-27b-uncensored"
_VLLM_MAX_TOKENS = 1024
_VLLM_TIMEOUT_SECONDS = 60
_CANARY_ENV_VAR = "LLM_DGA_VLLM_CANARY_PERCENT"
_DEFAULT_CANARY_PERCENT = 10
_VALID_VERDICTS = {"dga", "benign", "uncertain"}


def _get_canary_percent() -> int:
    raw_percent = os.environ.get(_CANARY_ENV_VAR)
    if raw_percent is None:
        return _DEFAULT_CANARY_PERCENT

    try:
        percent = int(raw_percent)
    except (TypeError, ValueError):
        return _DEFAULT_CANARY_PERCENT

    return max(0, min(100, percent))


def _in_canary_group(domain: str, percent: int) -> bool:
    bucket = int(
        hashlib.sha256(domain.encode("utf-8")).hexdigest()[:8],
        16,
    ) % 100
    return bucket < percent


def _uncertain(domain: str, error: str) -> Dict:
    return {
        "domain": domain,
        "llm_verdict": "uncertain",
        "llm_reasoning": "",
        "error": error,
    }


def _parse_json_response(response_text: str, provider: str) -> Dict:
    try:
        parsed = json.loads(response_text)
    except json.JSONDecodeError:
        json_match = re.search(
            r"```(?:json)?\s*(\{.*?\})\s*```",
            response_text,
            re.DOTALL,
        )
        if json_match:
            parsed = json.loads(json_match.group(1))
        else:
            start = response_text.find("{")
            end = response_text.rfind("}") + 1
            if start < 0 or end <= start:
                raise ValueError(f"Could not parse JSON from {provider} response")
            parsed = json.loads(response_text[start:end])

    if not isinstance(parsed, dict):
        raise ValueError(f"{provider} response JSON is not an object")

    return parsed


async def _judge_via_ollama(domain: str, config: Dict) -> Dict:
    llm_config = config.get("llm", {}) if isinstance(config, dict) else {}
    if not isinstance(llm_config, dict):
        llm_config = {}

    endpoint = llm_config.get("ollama_endpoint") or _DEFAULT_ENDPOINT
    model = llm_config.get("model") or _DEFAULT_MODEL

    prompt = (
        "Classify whether this domain appears to be generated by a "
        "Domain Generation Algorithm. Use only the domain string. "
        "Return JSON only in this exact shape: "
        '{"llm_verdict":"dga|benign|uncertain",'
        '"llm_reasoning":"short reasoning"}\n'
        f"Domain: {domain}"
    )

    payload = {
        "model": model,
        "prompt": prompt,
        "stream": False,
        "format": "json",
        "options": {
            "temperature": 0.2,
            "repeat_penalty": 1.3,
            "num_predict": 256,
        },
    }

    try:
        timeout = aiohttp.ClientTimeout(total=30)
        async with aiohttp.ClientSession(timeout=timeout) as session:
            async with session.post(
                f"{endpoint.rstrip('/')}/api/generate",
                json=payload,
            ) as response:
                if response.status != 200:
                    body = await response.text()
                    return _uncertain(
                        domain,
                        f"Ollama API error {response.status}: {body[:200]}",
                    )

                data = await response.json()
                parsed = _parse_json_response(data.get("response", ""), "Ollama")

                verdict = parsed.get("llm_verdict")
                if verdict not in _VALID_VERDICTS:
                    return _uncertain(
                        domain,
                        f"Invalid llm_verdict: {verdict!r}",
                    )

                reasoning = parsed.get("llm_reasoning", "")
                if not isinstance(reasoning, str):
                    reasoning = str(reasoning)

                return {
                    "domain": domain,
                    "llm_verdict": verdict,
                    "llm_reasoning": reasoning,
                    "error": None,
                }

    except aiohttp.ClientConnectorError as exc:
        logger.warning("[LLM-DGA] Cannot connect to Ollama: %s", exc)
        return _uncertain(domain, str(exc) or "Ollama connection failed")
    except asyncio.TimeoutError:
        logger.warning("[LLM-DGA] Ollama request timed out")
        return _uncertain(domain, "Ollama request timed out")
    except Exception as exc:
        logger.warning("[LLM-DGA] Judge failed: %s", exc)
        return _uncertain(domain, str(exc) or exc.__class__.__name__)


async def _judge_via_vllm(domain: str, config: Dict) -> Dict:
    llm_config = config.get("llm", {}) if isinstance(config, dict) else {}
    if not isinstance(llm_config, dict):
        llm_config = {}

    endpoint = llm_config.get(_VLLM_ENDPOINT_KEY)
    if not endpoint:
        return _uncertain(domain, "vLLM base URL not configured")

    prompt = (
        "Classify whether this domain appears to be generated by a "
        "Domain Generation Algorithm. Use only the domain string. "
        "Return JSON only in this exact shape: "
        '{"llm_verdict":"dga|benign|uncertain",'
        '"llm_reasoning":"short reasoning"}\n'
        f"Domain: {domain}"
    )
    payload = {
        "model": _VLLM_MODEL_OVERRIDE,
        "messages": [{"role": "user", "content": prompt}],
        "response_format": {"type": "json_object"},
        "max_tokens": _VLLM_MAX_TOKENS,
    }
    headers = {"Content-Type": "application/json"}
    api_key = llm_config.get("vllm_api_key")
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"

    try:
        timeout = aiohttp.ClientTimeout(total=_VLLM_TIMEOUT_SECONDS)
        async with aiohttp.ClientSession(timeout=timeout) as session:
            async with session.post(
                f"{endpoint.rstrip('/')}/v1/chat/completions",
                headers=headers,
                json=payload,
            ) as response:
                if response.status != 200:
                    body = await response.text()
                    return _uncertain(
                        domain,
                        f"vLLM API error {response.status}: {body[:200]}",
                    )

                data = await response.json()
                routing_info = (
                    data.get("extra_fields", {})
                    .get("routing_info", {})
                )
                if routing_info.get("is_fallback") is True:
                    logger.info("[LLM-DGA] vLLM request used a fallback route")

                choice = data["choices"][0]
                if choice.get("finish_reason") == "length":
                    logger.warning(
                        "[LLM-DGA] vLLM response truncated due to max_tokens "
                        "domain=%s max_tokens=%s",
                        domain,
                        _VLLM_MAX_TOKENS,
                    )
                    return _uncertain(
                        domain,
                        "vLLM response truncated due to max_tokens",
                    )

                content = choice["message"]["content"]
                parsed = _parse_json_response(content, "vLLM")

                verdict = parsed.get("llm_verdict")
                if verdict not in _VALID_VERDICTS:
                    return _uncertain(domain, f"Invalid llm_verdict: {verdict!r}")

                reasoning = parsed.get("llm_reasoning", "")
                if not isinstance(reasoning, str):
                    reasoning = str(reasoning)

                return {
                    "domain": domain,
                    "llm_verdict": verdict,
                    "llm_reasoning": reasoning,
                    "error": None,
                }

    except aiohttp.ClientConnectorError as exc:
        logger.warning(
            "[LLM-DGA] Cannot connect to vLLM (%s): %s",
            exc.__class__.__name__,
            exc,
        )
        return _uncertain(domain, str(exc) or "vLLM connection failed")
    except asyncio.TimeoutError as exc:
        logger.warning(
            "[LLM-DGA] vLLM request timed out (%s)",
            exc.__class__.__name__,
        )
        return _uncertain(domain, "vLLM request timed out")
    except Exception as exc:
        logger.warning(
            "[LLM-DGA] vLLM judge failed (%s): %s",
            exc.__class__.__name__,
            exc,
        )
        return _uncertain(domain, str(exc) or exc.__class__.__name__)


async def judge_domain(domain: str, config: Dict) -> Dict:
    if not _in_canary_group(domain, _get_canary_percent()):
        ollama_result = await _judge_via_ollama(domain, config)
        logger.info(
            "[LLM-DGA] canary=false provider=ollama domain=%s", domain
        )
        return ollama_result

    vllm_result = await _judge_via_vllm(domain, config)
    if vllm_result.get("error") is None:
        logger.info(
            "[LLM-DGA] canary=true provider=vllm domain=%s", domain
        )
        return vllm_result

    ollama_result = await _judge_via_ollama(domain, config)
    if ollama_result.get("error") is None:
        logger.info(
            "[LLM-DGA] canary=true provider=ollama domain=%s", domain
        )
        return ollama_result

    logger.warning("[LLM-DGA] both vLLM and Ollama failed; returning Ollama result")
    return ollama_result
